-- Script d'import généré — sociétés industrielles Dasolabs
-- Source : Entreprises_industrielles_Dasolabs.xlsx
-- Généré : 2026-10-07
-- Dédoublonné sur TVA. Idempotent via ON CONFLICT.

BEGIN;

-- Spa Monopole SA  (TVA BE0420834005)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp7d76e1d6eca2be452cf77', 'Spa Monopole SA', 'BE0420834005', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Spa Monopole', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp9a84445268030928c87c6', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0420834005'    OR ("vatNumber" IS NULL AND "name" = 'Spa Monopole SA') LIMIT 1), 'Spa', 'Usine / siège', 'Rue Auguste Laporte 34', '4900', 'Spa', 'Belgique', '+32 87 79 41 11', NULL, NULL, 'Documenté', 'https://www.spadel.com/fr/contact', 'Source: https://www.spadel.com/fr/contact · Source juridique: https://www.pappers.be/fr/company/spa-monopole-compagnie-fermiere-de-spa-0420.834.005', true, NOW(), NOW());

-- NLMK La Louvière SA  (TVA BE0417374172)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmpbc0c700b1d82d55c1963b', 'NLMK La Louvière SA', 'BE0417374172', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: NLMK La Louvière', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmpf420c520892f9996d7714', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0417374172'    OR ("vatNumber" IS NULL AND "name" = 'NLMK La Louvière SA') LIMIT 1), 'La Louvière', 'Usine / siège', 'Rue des Rivaux 2', '7100', 'La Louvière', 'Belgique', '+32 64 27 27 11', 'strip@eu.nlmk.com', NULL, 'Documenté', 'https://eu.nlmk.com/fr/contacts/?from=dk', 'Source: https://eu.nlmk.com/fr/contacts/?from=dk · Source juridique: https://www.pappers.be/fr/company/nlmk-la-louviere-0417374172', true, NOW(), NOW());

-- Nexans Benelux SA  (TVA BE0401782512)  — 2 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp97ab6e77c0e086ee548c8', 'Nexans Benelux SA', 'BE0401782512', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Nexans', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp13818fd7b48f0e7cd8b25', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0401782512'    OR ("vatNumber" IS NULL AND "name" = 'Nexans Benelux SA') LIMIT 1), 'Charleroi', 'Usine / siège', 'Rue Vital Françoisse 218', '6001', 'Marcinelle (Charleroi)', 'Belgique', NULL, NULL, NULL, 'Partiel', 'https://ecosystem.rewan.be/annuaire/nexans-belgium/', 'Source: https://ecosystem.rewan.be/annuaire/nexans-belgium/ · Source juridique: https://www.pappers.be/fr/company/nexans-benelux-0401.782.512 · Téléphones divergents selon les annuaires ; standard non retenu.', true, NOW(), NOW());
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmpd15f8897c8e7f465e2ee8', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0401782512'    OR ("vatNumber" IS NULL AND "name" = 'Nexans Benelux SA') LIMIT 1), 'Hal / Buizingen', 'Usine', 'Alsembergsesteenweg 2 b1', '1501', 'Buizingen (Hal)', 'Belgique', NULL, NULL, NULL, 'À confirmer', 'https://www.nexans.be/fr/company/Nexans-in-Belgium.html', 'Source: https://www.nexans.be/fr/company/Nexans-in-Belgium.html · Source juridique: https://www.pappers.be/fr/company/nexans-benelux-0401.782.512 · Adresse issue de documentation officielle ancienne ; à reconfirmer.', false, NOW(), NOW());

-- Vandemoortele NV  (TVA BE0429977343)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp41c94f96ecd29597a7645', 'Vandemoortele NV', 'BE0429977343', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Vandemoortele', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp0103932a4d274c71ab73e', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0429977343'    OR ("vatNumber" IS NULL AND "name" = 'Vandemoortele NV') LIMIT 1), 'Gand', 'Siège', 'Ottergemsesteenweg-Zuid 816', '9000', 'Gent', 'Belgique', '+32 9 240 18 00', NULL, NULL, 'Documenté', 'https://www.vandemoortele.com/fr-fr/informations-legales', 'Source: https://www.vandemoortele.com/fr-fr/informations-legales · Source juridique: https://www.pappers.be/fr/company/vandemoortele-0429977343 · Contact de l''entité NV ; Europe NV a un autre numéro BCE.', true, NOW(), NOW());

-- Flaurea Chemicals SA  (TVA BE0536756626)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp7dabde975bcb5deea6e50', 'Flaurea Chemicals SA', 'BE0536756626', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Flaurea Chemicals', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmpd48c4fe19f4ea6232314d', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0536756626'    OR ("vatNumber" IS NULL AND "name" = 'Flaurea Chemicals SA') LIMIT 1), 'Ath', 'Usine / siège', 'Quai des Usines 12', '7800', 'Ath', 'Belgique', '+32 68 28 19 12', NULL, NULL, 'Documenté', 'https://www.flaureachemicals.com/', 'Source: https://www.flaureachemicals.com/ · Source juridique: https://www.companyweb.be/fr/0536756626/flaurea-chemicals', true, NOW(), NOW());

-- Solarec SA  (TVA BE0442442140)  — 2 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmpfca26fd070f9ebde8d8e2', 'Solarec SA', 'BE0442442140', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Solarec', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp1ae6411eb599e83d41eb0', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0442442140'    OR ("vatNumber" IS NULL AND "name" = 'Solarec SA') LIMIT 1), 'Recogne', 'Production', 'Rue de Saint-Hubert 75', '6800', 'Libramont-Chevigny', 'Belgique', '+32 61 22 98 11', 'info@solarec.be', NULL, 'À confirmer', 'https://solarec.be/contact/', 'Source: https://solarec.be/contact/ · Source juridique: https://www.pappers.be/fr/company/solarec-0442442140 · Le site officiel indique siège Recogne ; source juridique indique Baudour. Adresse siège à arbitrer.', true, NOW(), NOW());
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmpcf30e6de096e3a82ac97c', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0442442140'    OR ("vatNumber" IS NULL AND "name" = 'Solarec SA') LIMIT 1), 'Baudour', 'Production', 'Rue des Azalées 3B', '7331', 'Baudour (Saint-Ghislain)', 'Belgique', '+32 61 24 13 35', 'info@solarec.be', NULL, 'À confirmer', 'https://solarec.be/contact/', 'Source: https://solarec.be/contact/ · Source juridique: https://www.pappers.be/fr/company/solarec-0442442140 · Contradiction entre siège publié sur site officiel et adresse juridique.', false, NOW(), NOW());

-- Vibrantz Minerals SRL  (TVA BE0403045985)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp577e1c37019bda693b641', 'Vibrantz Minerals SRL', 'BE0403045985', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Vibrantz', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp6ea1e254246ff1c8fc49f', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0403045985'    OR ("vatNumber" IS NULL AND "name" = 'Vibrantz Minerals SRL') LIMIT 1), 'Villerot', 'Usine', 'Rue du Bois s/n', '7334', 'Villerot (Saint-Ghislain)', 'Belgique', NULL, NULL, NULL, 'Partiel', 'https://vibrantz.com/our-company/global-locations/', 'Source: https://vibrantz.com/our-company/global-locations/ · Source juridique: https://www.companyweb.be/fr/0403045985/vibrantz-minerals · Téléphone général non confirmé.', true, NOW(), NOW());

-- Vibrantz Performance Pigments Belgium SA  (TVA BE0405467720)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmpc71eac3217f05730f8166', 'Vibrantz Performance Pigments Belgium SA', 'BE0405467720', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Vibrantz', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmpc52e5cc54a59daece254e', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0405467720'    OR ("vatNumber" IS NULL AND "name" = 'Vibrantz Performance Pigments Belgium SA') LIMIT 1), 'Menen', 'Usine', 'Kortrijkstraat 153', '8930', 'Menen', 'Belgique', NULL, NULL, NULL, 'Partiel', 'https://vibrantz.com/our-company/global-locations/', 'Source: https://vibrantz.com/our-company/global-locations/ · Source juridique: https://www.companyweb.be/fr/0405467720/vibrantz-performance-pigments-belgium · Téléphone général non confirmé.', true, NOW(), NOW());

-- Manufacture Belge de Chocolats  (TVA BE0722764519)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmpc9d8f70530130891e5d68', 'Manufacture Belge de Chocolats', 'BE0722764519', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: MBC', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmpaee309baec021c28ed56d', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0722764519'    OR ("vatNumber" IS NULL AND "name" = 'Manufacture Belge de Chocolats') LIMIT 1), 'Koekelberg', 'Usine', 'Rue Gemba 5', '1081', 'Koekelberg (Bruxelles)', 'Belgique', '+32 2 422 17 11', 'info@mbcchocolates.be', NULL, 'À confirmer', 'https://www.mbcchocolates.be/en/privacy-policy', 'Source: https://www.mbcchocolates.be/en/privacy-policy · Interprétation probable de MBC ; acronyme à confirmer par l''utilisateur.', true, NOW(), NOW());

-- Lotus Bakeries NV  (TVA BE0401030860)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp48e3b6d134b3a3d65fff0', 'Lotus Bakeries NV', 'BE0401030860', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Lotus', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmpa04b332e2c78af1fb0559', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0401030860'    OR ("vatNumber" IS NULL AND "name" = 'Lotus Bakeries NV') LIMIT 1), 'Lembeke', 'Siège', 'Gentstraat 1', '9971', 'Lembeke (Kaprijke)', 'Belgique', '+32 9 376 26 00', NULL, NULL, 'Documenté', 'https://www.lotusbakeries.com/nl/node/5', 'Source: https://www.lotusbakeries.com/nl/node/5 · Source juridique: https://www.companyweb.be/fr/0401030860/lotus-bakeries · Siège du groupe ; Lotus Bakeries België est une entité distincte.', true, NOW(), NOW());

-- Lotus Bakeries België NV  (TVA BE0421694038)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp6703f09dde0ad5cd08f7c', 'Lotus Bakeries België NV', 'BE0421694038', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Lotus', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp652f9e67b9e71820da6f3', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0421694038'    OR ("vatNumber" IS NULL AND "name" = 'Lotus Bakeries België NV') LIMIT 1), 'Lembeke', 'Contact Belgique', 'Gentstraat 52', '9971', 'Lembeke (Kaprijke)', 'Belgique', NULL, NULL, NULL, 'Partiel', 'https://www.lotusbakeries.be/nl/contact', 'Source: https://www.lotusbakeries.be/nl/contact · Source juridique: https://www.pappers.be/fr/company/lotus-bakeries-belgie-0421694038 · Standard propre à l''entité non confirmé.', true, NOW(), NOW());

-- Fuchs Lubricants Benelux NV/SA  (TVA BE0421493902)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmpfeacc60218c939ffecf01', 'Fuchs Lubricants Benelux NV/SA', 'BE0421493902', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Fuchs', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmpbb5f337957d6484cf8445', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0421493902'    OR ("vatNumber" IS NULL AND "name" = 'Fuchs Lubricants Benelux NV/SA') LIMIT 1), 'Huizingen', 'Siège / contact', 'Heideveld 54', '1654', 'Huizingen (Beersel)', 'Belgique', '+32 2 363 19 27', 'info-fbnl@fuchs.com', NULL, 'Documenté', 'https://www.fuchs.com/be/fr/entreprise/a-propos-de-fuchs/contact/', 'Source: https://www.fuchs.com/be/fr/entreprise/a-propos-de-fuchs/contact/ · Source juridique: https://www.companyweb.be/fr/0421493902/fuchs-lubricants-benelux-n-v-s-a-', true, NOW(), NOW());

-- Isomatex SA  (TVA BE0429395145)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp558f3bff4e45478ad2d33', 'Isomatex SA', 'BE0429395145', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Isomatex', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp115dc8c5bdd9a8a2534f1', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0429395145'    OR ("vatNumber" IS NULL AND "name" = 'Isomatex SA') LIMIT 1), 'Les Isnes', 'Usine / siège', 'Rue Camille Hubert 29', '5032', 'Les Isnes (Gembloux)', 'Belgique', '+32 81 72 86 86', 'info@isomatex.com', NULL, 'Documenté', 'https://www.isomatex.com/contact/', 'Source: https://www.isomatex.com/contact/ · Source juridique: https://www.pappers.be/fr/company/isomatex-0429395145', true, NOW(), NOW());

-- Minakem High Potent SA  (TVA BE0630942834)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp4b6d3626127c3e37479e2', 'Minakem High Potent SA', 'BE0630942834', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Minakem', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp7034fdcb3231fd7968def', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0630942834'    OR ("vatNumber" IS NULL AND "name" = 'Minakem High Potent SA') LIMIT 1), 'Mont-Saint-Guibert', 'Usine / siège', 'Rue Fonds Jean Pâques 8', '1435', 'Mont-Saint-Guibert', 'Belgique', '+32 10 23 81 80', NULL, NULL, 'Documenté', 'https://minakem.com/fr/nous-contacter/', 'Source: https://minakem.com/fr/nous-contacter/ · Source juridique: https://www.pappers.be/fr/company/minakem-high-potent-0630942834', true, NOW(), NOW());

-- BI Belgium (ENG) SRL  (TVA BE0825917386)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp68177303a5e334e264437', 'BI Belgium (ENG) SRL', 'BE0825917386', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Biscuit International', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp2ce20c7390134f91f5865', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0825917386'    OR ("vatNumber" IS NULL AND "name" = 'BI Belgium (ENG) SRL') LIMIT 1), 'Enghien', 'Usine', 'Avenue du Commerce 27', '7850', 'Enghien', 'Belgique', NULL, 'info_BE@biscuitinternational.com', NULL, 'Partiel', 'https://www.biscuitinternational.com/company/international-market/belgium/', 'Source: https://www.biscuitinternational.com/company/international-market/belgium/ · Source juridique: https://www.pappers.be/fr/company/biscuit-international-belgium-eng-0825917386 · Le téléphone publié pour le contact Benelux est néerlandais, pas un standard belge.', true, NOW(), NOW());

-- BI Belgium (GHI) SRL  (TVA BE0435235238)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmpf68372a5346b2dc95b0ec', 'BI Belgium (GHI) SRL', 'BE0435235238', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Biscuit International', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp709a8273b8f093784d195', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0435235238'    OR ("vatNumber" IS NULL AND "name" = 'BI Belgium (GHI) SRL') LIMIT 1), 'Ghislenghien', 'Usine', 'Rue des Journaliers 6 boîte B', '7822', 'Ghislenghien (Ath)', 'Belgique', NULL, 'info_BE@biscuitinternational.com', NULL, 'Partiel', 'https://trendstop.levif.be/fr/detail/435235238/biscuit-international-belgium-ghi.aspx', 'Source: https://trendstop.levif.be/fr/detail/435235238/biscuit-international-belgium-ghi.aspx · Source juridique: https://www.pappers.be/fr/company/biscuit-international-belgium-ghi-0435235238 · Standard propre au site non confirmé.', true, NOW(), NOW());

-- Hydria  (TVA BE0884649502)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp971ba336f1fea69d4db65', 'Hydria', 'BE0884649502', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: SBGE', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp5f41122424b39279bfa86', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0884649502'    OR ("vatNumber" IS NULL AND "name" = 'Hydria') LIMIT 1), 'Bruxelles', 'Siège', 'Boulevard de l''Impératrice 17', '1000', 'Bruxelles', 'Belgique', '+32 2 505 47 10', 'info@hydria.be', NULL, 'Documenté', 'https://hydria.be/fr/nous-contacter/', 'Source: https://hydria.be/fr/nous-contacter/ · Ancienne SBGE ; dénomination Hydria depuis 2021.', true, NOW(), NOW());

-- Mondelez Belgium SRL  (TVA BE0821674726)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp7153c8a7ef7bfa904c1bf', 'Mondelez Belgium SRL', 'BE0821674726', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Mondelez', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp37ab441aa2b4d497de3f9', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0821674726'    OR ("vatNumber" IS NULL AND "name" = 'Mondelez Belgium SRL') LIMIT 1), 'Malines', 'Siège / contact', 'Stationsstraat 100', '2800', 'Mechelen', 'Belgique', '+32 15 74 35 00', NULL, NULL, 'Documenté', 'https://www.mondelezinternational.com/europe/contact-us/', 'Source: https://www.mondelezinternational.com/europe/contact-us/ · Source juridique: https://www.companyweb.be/fr/0821674726/mondelez-belgium · Contact Belgique ; usines du groupe non inventoriées intégralement.', true, NOW(), NOW());

-- Materne-Confilux SA  (TVA BE0401408863)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp721b390dbe812767dd803', 'Materne-Confilux SA', 'BE0401408863', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Materne', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp21a37923a6d58ee8f9af4', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0401408863'    OR ("vatNumber" IS NULL AND "name" = 'Materne-Confilux SA') LIMIT 1), 'Floreffe', 'Usine / siège', 'Allée des Cerisiers 1', '5150', 'Floreffe', 'Belgique', '+32 81 44 74 74', NULL, NULL, 'Documenté', 'https://www.materne.be/policies/legal-notice', 'Source: https://www.materne.be/policies/legal-notice · Source juridique: https://www.pappers.be/fr/company/materne-confilux-0401408863 · Téléphone du service client publié sur la page contact.', true, NOW(), NOW());

-- Krones SA/NV  (TVA BE0428305775)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmpcf1d6d6f93ff0e65079ec', 'Krones SA/NV', 'BE0428305775', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Krones', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp24855c53f9fb5a6f11ce8', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0428305775'    OR ("vatNumber" IS NULL AND "name" = 'Krones SA/NV') LIMIT 1), 'Louvain-la-Neuve Sud', 'Service / formation', 'Rue du Bosquet 17', '1348', 'Louvain-la-Neuve', 'Belgique', '+32 10 48 07 00', 'krones@krones.be', NULL, 'Documenté', 'https://www.krones.com/en/belgium.php', 'Source: https://www.krones.com/en/belgium.php · Source juridique: https://www.pappers.be/fr/company/krones-0428305775', true, NOW(), NOW());

-- Vital Materials Belgium SA  (TVA BE0400355226)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmpe4f30c52b4b4b6a42b285', 'Vital Materials Belgium SA', 'BE0400355226', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: 5N+', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmpd60cd9e10103431fc0a34', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0400355226'    OR ("vatNumber" IS NULL AND "name" = 'Vital Materials Belgium SA') LIMIT 1), 'Tilly', 'Usine', 'Rue de la Station 67', '1495', 'Tilly (Villers-la-Ville)', 'Belgique', NULL, NULL, NULL, 'Partiel', 'https://www.pappers.be/fr/company/vital-materials-belgium-0400355226', 'Source: https://www.pappers.be/fr/company/vital-materials-belgium-0400355226 · Ancien 5N Plus Belgium, cédé à Vital Materials en décembre 2022. Anciennes coordonnées 5N+ non reprises.', true, NOW(), NOW());

-- Lasea SA  (TVA BE0465268616)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp8526d45cb997079b018a5', 'Lasea SA', 'BE0465268616', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Lasea', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmpf4bf4bf2ca9d4109ebc36', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0465268616'    OR ("vatNumber" IS NULL AND "name" = 'Lasea SA') LIMIT 1), 'Seraing', 'Siège / production', 'Rue Louis Plescia 31', '4102', 'Seraing', 'Belgique', '+32 4 365 02 43', 'info@lasea.com', NULL, 'Documenté', 'https://lasea.com/privacy-policy/', 'Source: https://lasea.com/privacy-policy/ · Source juridique: https://www.companyweb.be/fr/0465268616/laser-engineering-applications', true, NOW(), NOW());

-- NGK Ceramics Europe SA  (TVA BE0401115388)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp7cac8fc467af98b08a836', 'NGK Ceramics Europe SA', 'BE0401115388', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: NGK', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp4fffc1db6ab517994e90d', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0401115388'    OR ("vatNumber" IS NULL AND "name" = 'NGK Ceramics Europe SA') LIMIT 1), 'Baudour', 'Usine / siège', 'Rue des Azalées 1', '7331', 'Baudour (Saint-Ghislain)', 'Belgique', '+32 65 76 02 10', NULL, NULL, 'Documenté', 'https://www.ngkceramicseurope.be/fr/nous-contacter', 'Source: https://www.ngkceramicseurope.be/fr/nous-contacter', true, NOW(), NOW());

-- Holcim (Belgique) SA  (TVA BE0437977764)  — 2 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp138bbd38892e31b516ec8', 'Holcim (Belgique) SA', 'BE0437977764', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Holcim', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp33afeb0a74d1121df48df', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0437977764'    OR ("vatNumber" IS NULL AND "name" = 'Holcim (Belgique) SA') LIMIT 1), 'Nivelles', 'Siège', 'Avenue Robert Schuman 71', '1401', 'Nivelles', 'Belgique', '+32 67 87 66 01', 'marketing-be@holcim.com', NULL, 'Documenté', 'https://www.holcim.be/fr/mentions-legales', 'Source: https://www.holcim.be/fr/mentions-legales', true, NOW(), NOW());
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmpe6cb8665be454dbdf2482', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0437977764'    OR ("vatNumber" IS NULL AND "name" = 'Holcim (Belgique) SA') LIMIT 1), 'Obourg', 'Cimenterie', 'Rue des Fabriques 2', '7034', 'Obourg (Mons)', 'Belgique', NULL, NULL, NULL, 'Partiel', 'https://www.holcim.be/sites/belgium/files/docs/n_86_66-2025_02_03-certificat-nf-obourg.pdf', 'Source: https://www.holcim.be/sites/belgium/files/docs/n_86_66-2025_02_03-certificat-nf-obourg.pdf · Standard local non confirmé.', false, NOW(), NOW());

-- Pharma Technology SA  (TVA BE0443803803)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp26ecabc7ae46bee753fb5', 'Pharma Technology SA', 'BE0443803803', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Pharma Technology', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp1e966e3891d34f0cf8f14', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0443803803'    OR ("vatNumber" IS NULL AND "name" = 'Pharma Technology SA') LIMIT 1), 'Thines', 'Siège / production', 'Rue Graham Bell 8', '1402', 'Thines (Nivelles)', 'Belgique', '+32 67 70 13 00', NULL, NULL, 'Documenté', 'https://www.pharmatec.be/contactus', 'Source: https://www.pharmatec.be/contactus · Source juridique: https://www.pappers.be/fr/company/pharma-technology-0443803803', true, NOW(), NOW());

-- Westinghouse Electric Belgium SA  (TVA BE0449543728)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp3c0f6e7e09d343bcef0fc', 'Westinghouse Electric Belgium SA', 'BE0449543728', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Westinghouse', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp9c879ec8acfdd2aa89aad', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0449543728'    OR ("vatNumber" IS NULL AND "name" = 'Westinghouse Electric Belgium SA') LIMIT 1), 'Nivelles', 'Siège / services', 'Rue de l''Industrie 43', '1400', 'Nivelles', 'Belgique', '+32 67 28 81 11', NULL, NULL, 'Documenté', 'https://westinghousenuclear.com/about/locations', 'Source: https://westinghousenuclear.com/about/locations · Source juridique: https://www.pappers.be/fr/company/westinghouse-electric-belgium-0449543728', true, NOW(), NOW());

-- PolyPeptide SA  (TVA BE0879346768)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmpb6a8b7c5bb2acd1abf81a', 'PolyPeptide SA', 'BE0879346768', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Polypeptide', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp98d2756a2b647318193a5', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0879346768'    OR ("vatNumber" IS NULL AND "name" = 'PolyPeptide SA') LIMIT 1), 'Braine-l''Alleud', 'Usine / siège', 'Chaussée de Tubize 297', '1420', 'Braine-l''Alleud', 'Belgique', '+32 2 386 29 09', NULL, NULL, 'Documenté', 'https://www.polypeptide.com/contacts/', 'Source: https://www.polypeptide.com/contacts/ · Source juridique: https://www.pappers.be/fr/company/polypeptide-0879346768', true, NOW(), NOW());

-- Cenexi - Laboratoires Thissen SA  (TVA BE0843115684)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp7407ec473012b1afcf68d', 'Cenexi - Laboratoires Thissen SA', 'BE0843115684', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Cenexi', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmpd2be1342596de0b8ec9f4', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0843115684'    OR ("vatNumber" IS NULL AND "name" = 'Cenexi - Laboratoires Thissen SA') LIMIT 1), 'Braine-l''Alleud', 'Usine / siège', 'Rue de la Papyrée 2-4-6', '1420', 'Braine-l''Alleud', 'Belgique', '+32 2 386 13 01', NULL, NULL, 'Documenté', 'https://www.cenexi.com/mentions-legales/', 'Source: https://www.cenexi.com/mentions-legales/ · Source juridique: https://www.pappers.be/fr/company/cenexi-laboratoires-thissen-0843115684', true, NOW(), NOW());

-- Catalent Belgium SA/NV  (TVA BE0465935738)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmpfa12f5898f2d4c797e9d1', 'Catalent Belgium SA/NV', 'BE0465935738', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Catalent', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmpb6511e74e65e2f7db9b14', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0465935738'    OR ("vatNumber" IS NULL AND "name" = 'Catalent Belgium SA/NV') LIMIT 1), 'Bruxelles', 'Site publié', 'Boulevard Emile Bockstael 88', '1020', 'Bruxelles', 'Belgique', '+32 2 426 73 94', NULL, NULL, 'À confirmer', 'https://www.essenscia.be/fr/chimie-sciences-de-la-vie/nos-membres/catalent-belgium-3/', 'Source: https://www.essenscia.be/fr/chimie-sciences-de-la-vie/nos-membres/catalent-belgium-3/ · Fiche sectorielle ; activité et exploitant actuels à confirmer avant prospection.', true, NOW(), NOW());

-- BePharBel Manufacturing SA  (TVA BE0844689955)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp097eda1f04a7ff4e88565', 'BePharBel Manufacturing SA', 'BE0844689955', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Bepharbel', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp717fd91b2f1c8fda1ce70', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0844689955'    OR ("vatNumber" IS NULL AND "name" = 'BePharBel Manufacturing SA') LIMIT 1), 'Courcelles', 'Usine / siège', 'Rue du Luxembourg 13', '6180', 'Courcelles', 'Belgique', '+32 71 46 60 60', 'info@bepharbel.com', NULL, 'Documenté', 'https://www.bepharbel.com/cgu/', 'Source: https://www.bepharbel.com/cgu/ · Source juridique: https://www.pappers.be/fr/company/bepharbel-manufacturing-0844689955 · Entité Manufacturing ; BePharBel SA porte un autre numéro BCE.', true, NOW(), NOW());

-- Unilin BV  (TVA BE0405414072)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp38b73860ff7f8691bb187', 'Unilin BV', 'BE0405414072', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Unilin', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp90249a1076c1056b33cc2', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0405414072'    OR ("vatNumber" IS NULL AND "name" = 'Unilin BV') LIMIT 1), 'Wielsbeke', 'Siège', 'Ooigemstraat 3', '8710', 'Wielsbeke', 'Belgique', '+32 56 67 52 14', 'info@unilin.com', NULL, 'Documenté', 'https://www.wvi.be/ondernemer/terreinbeheer/zoek-een-bedrijf/unilin', 'Source: https://www.wvi.be/ondernemer/terreinbeheer/zoek-een-bedrijf/unilin · Source juridique: https://www.companyweb.be/fr/0405414072/unilin · Téléphone annuaire WVI ; sites industriels non exhaustifs.', true, NOW(), NOW());

-- Carmeuse SA  (TVA BE0431473519)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp972c9631b36d7d4c6b5c2', 'Carmeuse SA', 'BE0431473519', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Carmeuse', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp6a1e058ae74dd8b8481e0', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0431473519'    OR ("vatNumber" IS NULL AND "name" = 'Carmeuse SA') LIMIT 1), 'Seilles', 'Usine / contact', 'Rue du Château 13A', '5300', 'Seilles (Andenne)', 'Belgique', '+32 85 83 01 11', NULL, NULL, 'Documenté', 'https://www.carmeuse.com/eu-fr/contactez-nous', 'Source: https://www.carmeuse.com/eu-fr/contactez-nous · Source juridique: https://www.companyweb.be/fr/0431473519/carmeuse · Plusieurs sites du groupe ; ligne ciblée Seilles.', true, NOW(), NOW());

-- AGC Glass Europe SA  (TVA BE0413638187)  — 3 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmpda8ee6ad30d669f3f634a', 'AGC Glass Europe SA', 'BE0413638187', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: AGC', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp8a0d8190c551659a99644', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0413638187'    OR ("vatNumber" IS NULL AND "name" = 'AGC Glass Europe SA') LIMIT 1), 'Louvain-la-Neuve', 'Siège', 'Avenue Jean Monnet 4', '1348', 'Louvain-la-Neuve', 'Belgique', '+32 2 409 30 00', 'Glass.Communications@agc.com', NULL, 'Documenté', 'https://www.agc-glass.eu/fr/mentions-legales', 'Source: https://www.agc-glass.eu/fr/mentions-legales · Adresse mail institutionnelle / communication.', true, NOW(), NOW());
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmpf2beb5d27717cb47d556a', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0413638187'    OR ("vatNumber" IS NULL AND "name" = 'AGC Glass Europe SA') LIMIT 1), 'Moustier', 'Usine', 'Rue de la Glacerie 167', '5190', 'Moustier-sur-Sambre', 'Belgique', NULL, NULL, NULL, 'Partiel', 'https://www.agc-glass.eu/sites/default/files/2026-01/Directory-invoicing-email-addresses_1.pdf', 'Source: https://www.agc-glass.eu/sites/default/files/2026-01/Directory-invoicing-email-addresses_1.pdf · Adresse de facturation du site ; standard local non confirmé.', false, NOW(), NOW());
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp27910e420ca365b2d8e4f', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0413638187'    OR ("vatNumber" IS NULL AND "name" = 'AGC Glass Europe SA') LIMIT 1), 'Mol', 'Usine', 'Voortstraat 27', '2400', 'Mol', 'Belgique', NULL, NULL, NULL, 'Partiel', 'https://www.agc-glass.eu/sites/default/files/2026-01/Directory-invoicing-email-addresses_1.pdf', 'Source: https://www.agc-glass.eu/sites/default/files/2026-01/Directory-invoicing-email-addresses_1.pdf · Adresse de facturation du site ; standard local non confirmé.', false, NOW(), NOW());

-- Besins Healthcare SA  (TVA BE0473343667)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp2c6a94d8078ce85259ed6', 'Besins Healthcare SA', 'BE0473343667', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Besins', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp1b50ec1bf698557ef86c1', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0473343667'    OR ("vatNumber" IS NULL AND "name" = 'Besins Healthcare SA') LIMIT 1), 'Ixelles', 'Contact Belgique', 'Rue Washington 80', '1050', 'Ixelles (Bruxelles)', 'Belgique', '+32 52 25 75 84', 'info@besins-healthcare.be', NULL, 'Documenté', 'https://www.besins-healthcare.be/fr/contacter/', 'Source: https://www.besins-healthcare.be/fr/contacter/ · Source juridique: https://www.pappers.be/fr/company/besins-healthcare-0473343667 · Entité commerciale ; site de production à préciser si nécessaire.', true, NOW(), NOW());

-- Prothya Biosolutions Belgium SRL  (TVA BE0462229645)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp3c891edd22520d49123ca', 'Prothya Biosolutions Belgium SRL', 'BE0462229645', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Prothya', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmpd3be2490221bea7f581e2', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0462229645'    OR ("vatNumber" IS NULL AND "name" = 'Prothya Biosolutions Belgium SRL') LIMIT 1), 'Neder-over-Heembeek', 'Usine / siège', 'Avenue de Tyras 109', '1120', 'Bruxelles', 'Belgique', '+32 2 264 64 11', 'info@prothya.com', NULL, 'Documenté', 'https://prothya.com/contact/', 'Source: https://prothya.com/contact/ · Source juridique: https://www.pappers.be/fr/company/prothya-biosolutions-belgium-0462229645', true, NOW(), NOW());

-- Société Nationale de Construction Aérospatiale SA  (TVA BE0418217577)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp795b2b7223edf6d442957', 'Société Nationale de Construction Aérospatiale SA', 'BE0418217577', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Sonaca', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmpc0d8b8f1c449f4b19ead5', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0418217577'    OR ("vatNumber" IS NULL AND "name" = 'Société Nationale de Construction Aérospatiale SA') LIMIT 1), 'Gosselies', 'Usine / siège', 'Route Nationale 5 s/n', '6041', 'Gosselies (Charleroi)', 'Belgique', NULL, 'communication@sonaca.com', NULL, 'Partiel', 'https://www.sonaca.com/fr/a-propos-de-sonaca/', 'Source: https://www.sonaca.com/fr/a-propos-de-sonaca/ · Source juridique: https://www.companyweb.be/fr/0418217577/societe-nationale-de-construction-aerospatiale · Standard général non confirmé ; numéro d''un service non substitué.', true, NOW(), NOW());

-- TotalEnergies Petrochemicals Feluy SA  (TVA BE0416670824)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp711e9846d4981a74dbf2b', 'TotalEnergies Petrochemicals Feluy SA', 'BE0416670824', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Total Energy', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp8f081acd89bd28b8d5cbc', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0416670824'    OR ("vatNumber" IS NULL AND "name" = 'TotalEnergies Petrochemicals Feluy SA') LIMIT 1), 'Feluy', 'Usine', 'Parc Industriel de Feluy s/n', '7181', 'Feluy (Seneffe)', 'Belgique', NULL, NULL, NULL, 'À confirmer', 'https://www.pappers.be/fr/company/totalenergies-petrochemicals-feluy-0416670824', 'Source: https://www.pappers.be/fr/company/totalenergies-petrochemicals-feluy-0416670824 · Source juridique: https://www.pappers.be/fr/company/totalenergies-petrochemicals-feluy-0416670824 · Choix industriel probable ; groupe comporte plusieurs entités sur le site. Standard non confirmé.', true, NOW(), NOW());

-- Lhoist SA  (TVA BE0459399522)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp817e537996472c081486c', 'Lhoist SA', 'BE0459399522', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Lhoist', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmpf96dc18b3e60f018f7fda', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0459399522'    OR ("vatNumber" IS NULL AND "name" = 'Lhoist SA') LIMIT 1), 'Limelette', 'Contact groupe', 'Rue Charles Dubois 28', '1342', 'Limelette (Ottignies)', 'Belgique', '+32 10 23 07 11', 'info@lhoist.com', NULL, 'Documenté', 'https://www.lhoist.com/fr-BX/mentions-legales-belgique', 'Source: https://www.lhoist.com/fr-BX/mentions-legales-belgique · Source juridique: https://www.pappers.be/fr/company/lhoist-0459.399.522 · Source juridique consultée indique Rue de l''Industrie 31, 1400 Nivelles ; adresse officielle de contact distincte.', true, NOW(), NOW());

-- Puratos NV  (TVA BE0438632416)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp7e5e0f34be0501d79f96f', 'Puratos NV', 'BE0438632416', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Puratos', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmpc1416e2f82b1ba3cf77dd', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0438632416'    OR ("vatNumber" IS NULL AND "name" = 'Puratos NV') LIMIT 1), 'Grand-Bigard', 'Siège / contact', 'Industrialaan 25', '1702', 'Grand-Bigard (Dilbeek)', 'Belgique', '+32 2 481 44 44', 'info@puratos.be', NULL, 'Documenté', 'https://www.puratos.be/fr/contactez_nous', 'Source: https://www.puratos.be/fr/contactez_nous · Source juridique: https://www.pappers.be/fr/company/puratos-0438632416', true, NOW(), NOW());

-- Coca-Cola Europacific Partners Belgium SRL  (TVA BE0425071420)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp0c3e5f9808de82c767faf', 'Coca-Cola Europacific Partners Belgium SRL', 'BE0425071420', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Coca Cola', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp35e2050ce4115e5d24615', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0425071420'    OR ("vatNumber" IS NULL AND "name" = 'Coca-Cola Europacific Partners Belgium SRL') LIMIT 1), 'Anderlecht', 'Siège', 'Chaussée de Mons 1424', '1070', 'Anderlecht', 'Belgique', '+32 2 559 20 00', 'hello@ccep.com', NULL, 'Documenté', 'https://www.coca-cola.com/be/fr/about-us/contact-us', 'Source: https://www.coca-cola.com/be/fr/about-us/contact-us · hello@ccep.com est un contact client.', true, NOW(), NOW());

-- Anheuser-Busch InBev  (TVA BE0417497106)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmpfa40cdb43489383215be5', 'Anheuser-Busch InBev', 'BE0417497106', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: AB Inbev', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmpf7fb53fed51d3324977a5', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0417497106'    OR ("vatNumber" IS NULL AND "name" = 'Anheuser-Busch InBev') LIMIT 1), 'Louvain', 'Contact groupe', 'Brouwerijplein 1', '3000', 'Leuven', 'Belgique', '0800 58 316', 'cx.horeca@ab-inbev.com', NULL, 'Documenté', 'https://www.ab-inbev.be/fr/contact', 'Source: https://www.ab-inbev.be/fr/contact · Source juridique: https://www.pappers.be/fr/company/anheuser-busch-inbev-nv-0417497106 · Numéro de contact publié, gratuit et non fixe géographique. Plusieurs entités juridiques ; siège à confirmer dans BCE.', true, NOW(), NOW());

-- Thales Belgium SA  (TVA BE0434342145)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmpcdedf1c5dec8010384331', 'Thales Belgium SA', 'BE0434342145', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Thales', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp9df26a104c554a1dcc749', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0434342145'    OR ("vatNumber" IS NULL AND "name" = 'Thales Belgium SA') LIMIT 1), 'Herstal', 'Usine / siège', 'Rue En Bois 63', '4040', 'Herstal', 'Belgique', '+32 2 391 22 11', 'info@be.thalesgroup.com', NULL, 'Documenté', 'https://clusters.wallonie.be/sites/infopole/home/membres/memberList/thales-belgium.html', 'Source: https://clusters.wallonie.be/sites/infopole/home/membres/memberList/thales-belgium.html · Source juridique: https://www.pappers.be/fr/company/thales-belgium-0434342145 · Téléphone central publié dans fiche sectorielle ; ne pas confondre avec thales.be (cabinet juridique).', true, NOW(), NOW());

-- Veolia NV/SA  (TVA BE0406129003)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmpfdddb3107809e44b30d16', 'Veolia NV/SA', 'BE0406129003', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Veolia', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp74d4480c0b2f0223fd89c', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0406129003'    OR ("vatNumber" IS NULL AND "name" = 'Veolia NV/SA') LIMIT 1), 'Bruxelles', 'Siège / contact', 'Boulevard Poincaré 78-79', '1060', 'Saint-Gilles (Bruxelles)', 'Belgique', '+32 2 789 70 30', NULL, NULL, 'Documenté', 'https://www.veolia.be/fr/numero-dentreprise', 'Source: https://www.veolia.be/fr/numero-dentreprise · Autres activités Veolia portées par des sociétés distinctes.', true, NOW(), NOW());

-- Société wallonne des eaux  (sans TVA)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp99fc5298a87fca58d5ece', 'Société wallonne des eaux', NULL, 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: SWDE', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp552dfa8cb637af3091744', (SELECT "id" FROM "Company" WHERE "vatNumber" = NULL    OR ("vatNumber" IS NULL AND "name" = 'Société wallonne des eaux') LIMIT 1), 'Verviers', 'Siège', 'Rue de la Concorde 41', '4800', 'Verviers', 'Belgique', '+32 87 87 87 87', NULL, NULL, 'Documenté', 'https://www.swde.be/fr/politique-de-protection-de-la-vie-privee', 'Source: https://www.swde.be/fr/politique-de-protection-de-la-vie-privee · Téléphone service client ; source https://www.swde.be/fr/autres-demandes. Activation TVA non vérifiée.', true, NOW(), NOW());

-- in BW Association Intercommunale  (TVA BE0200362210)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp066793f6ec1955d002421', 'in BW Association Intercommunale', 'BE0200362210', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: in BW', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp2b418fa4923c6aaec3ede', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0200362210'    OR ("vatNumber" IS NULL AND "name" = 'in BW Association Intercommunale') LIMIT 1), 'Nivelles', 'Siège', 'Rue de la Religion 10', '1400', 'Nivelles', 'Belgique', '+32 67 21 71 11', 'direction@inbw.be', NULL, 'Documenté', 'https://www.inbw.be/sites/default/files/2025-12/Déclaration%20environnementale%2025.pdf', 'Source: https://www.inbw.be/sites/default/files/2025-12/Déclaration%20environnementale%2025.pdf · Numéro TVA publié dans procès-verbaux du groupe.', true, NOW(), NOW());

-- Dow Silicones Belgium SRL  (TVA BE0406117818)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp6ef030dde0980a8331e6c', 'Dow Silicones Belgium SRL', 'BE0406117818', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Dow Silicone', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmpfea36ff49b4900bece221', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0406117818'    OR ("vatNumber" IS NULL AND "name" = 'Dow Silicones Belgium SRL') LIMIT 1), 'Seneffe', 'Usine / siège', 'Rue Jules Bordet C', '7180', 'Seneffe', 'Belgique', '+32 64 88 80 00', NULL, NULL, 'Documenté', 'https://be.dow.com/fr-be/locations.html', 'Source: https://be.dow.com/fr-be/locations.html · Source juridique: https://www.pappers.be/fr/company/dow-silicones-belgium-0406117818', true, NOW(), NOW());

-- Desimone  (TVA BE0441135610)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmpc89fb2f294a41f893057f', 'Desimone', 'BE0441135610', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', NULL, NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmpe0f7df37d9337692378e7', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0441135610'    OR ("vatNumber" IS NULL AND "name" = 'Desimone') LIMIT 1), 'Farciennes', 'Siège / atelier', 'Rue Fontenelle 18', '6240', 'Farciennes', 'Belgique', '+32 71 81 18 59', 'info@desimone.be', NULL, 'Documenté', 'https://www.desimone.be/contact-desimone/', 'Source: https://www.desimone.be/contact-desimone/', true, NOW(), NOW());

-- Eutomation & Scansys SRL  (TVA BE0896948706)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp696088673ae0f3c017922', 'Eutomation & Scansys SRL', 'BE0896948706', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Eutomation', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp91ef168287ebc014eb0f7', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0896948706'    OR ("vatNumber" IS NULL AND "name" = 'Eutomation & Scansys SRL') LIMIT 1), 'Eupen', 'Siège / atelier', 'Industriestraße 28B', '4700', 'Eupen', 'Belgique', '+32 87 56 10 08', 'info@eutomation.be', NULL, 'Documenté', 'https://www.eutomation.be/fr/contact', 'Source: https://www.eutomation.be/fr/contact', true, NOW(), NOW());

-- AgiNtech SRL  (TVA BE0770511481)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmpf2e7698d3698a45b29972', 'AgiNtech SRL', 'BE0770511481', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Agintech', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmp51d274ea5122730c48b77', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0770511481'    OR ("vatNumber" IS NULL AND "name" = 'AgiNtech SRL') LIMIT 1), 'Ham-sur-Sambre', 'Siège / contact', 'Rue Emile Vandervelde 56C', '5190', 'Ham-sur-Sambre', 'Belgique', '+32 71 25 62 80', 'contact@agintech.eu', NULL, 'Documenté', 'https://agintech.eu/mentions-legales/', 'Source: https://agintech.eu/mentions-legales/ · Source juridique: https://www.pappers.be/fr/company/agintech-0770511481', true, NOW(), NOW());

-- BAIPS SA  (TVA BE0765934566)  — 1 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp464304c3053f2bd27dac7', 'BAIPS SA', 'BE0765934566', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: BAIPS', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmpa3c2948387b0bbb2b1856', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE0765934566'    OR ("vatNumber" IS NULL AND "name" = 'BAIPS SA') LIMIT 1), 'Nivelles', 'Siège', 'Avenue Robert Schuman 42', '1401', 'Nivelles', 'Belgique', NULL, NULL, NULL, 'Partiel', 'https://www.pappers.be/fr/company/baips-0765934566', 'Source: https://www.pappers.be/fr/company/baips-0765934566 · Source juridique: https://www.pappers.be/fr/company/baips-0765934566 · Aucun standard confirmé. Ne pas reprendre celui d''IPS Belgium sans preuve.', true, NOW(), NOW());

-- Endexia SRL  (TVA BE1011049311)  — 2 site(s)
INSERT INTO "Company" ("id", "name", "vatNumber", "sector", "status", "source", "country", "notes", "createdAt", "updatedAt") VALUES ('cmp481f439753ba9451a35b6', 'Endexia SRL', 'BE1011049311', 'Industrie', 'PROSPECT', 'Import Excel 2026-10-07', 'Belgique', 'Nom fourni: Endexia', NOW(), NOW()) ON CONFLICT ("vatNumber") DO NOTHING;
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmpfb7d5683c8c2df380e718', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE1011049311'    OR ("vatNumber" IS NULL AND "name" = 'Endexia SRL') LIMIT 1), 'Rixensart', 'Siège', 'Avenue John Kennedy 29', '1330', 'Rixensart', 'Belgique', '+32 2 466 61 69', 'info@endexia.com', NULL, 'Documenté', 'https://endexia.com/contact-us/', 'Source: https://endexia.com/contact-us/ · Source juridique: https://www.companyweb.be/fr/1011049311/endexia', true, NOW(), NOW());
INSERT INTO "CompanySite" ("id", "companyId", "name", "siteType", "street", "postalCode", "city", "country", "phone", "email", "establishmentUnit", "verificationStatus", "sourceUrl", "notes", "isPrimary", "createdAt", "updatedAt") VALUES ('cmpd8572cd9309c0adfaee16', (SELECT "id" FROM "Company" WHERE "vatNumber" = 'BE1011049311'    OR ("vatNumber" IS NULL AND "name" = 'Endexia SRL') LIMIT 1), 'Wavre', 'Bureau', 'Avenue Pasteur 2', '1300', 'Wavre', 'Belgique', '+32 2 466 61 69', 'info@endexia.com', NULL, 'Documenté', 'https://endexia.com/contact-us/', 'Source: https://endexia.com/contact-us/ · Source juridique: https://www.companyweb.be/fr/1011049311/endexia · Téléphone central partagé.', false, NOW(), NOW());

COMMIT;

-- Récap : 51 société(s) · 57 site(s)