version: "3.9"
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: dasolabs
      POSTGRES_PASSWORD: dasolabs
      POSTGRES_DB: dasolabs
    ports:
      - "5432:5432"
    volumes:
      - dasolabs_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U dasolabs -d dasolabs"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://dasolabs:dasolabs@db:5432/dasolabs?schema=public
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: change-me-in-production-use-openssl-rand-base64-32
    ports:
      - "3000:3000"

volumes:
  dasolabs_db:
